import{load,save,backup,restore,merge}from'./storage.js';
import{assets,storeStats}from'./calculations.js';
import{id,importLegacy}from'./schema.js';
import{applyPurchase,applySale,applyOpening}from'./inventory.js';

let state=load();let route=location.hash.slice(1)||'dashboard';let subtype='purchases';let calendarMonth=(new Date()).toISOString().slice(0,7);let selectedCalendarDate=(new Date()).toISOString().slice(0,10);
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat('ja-JP',{month:'short',day:'numeric',weekday:'short'});
const nav=[['dashboard','⌂','資産'],['calendar','□','予定'],['ledger','¥','収支'],['inventory','▦','在庫'],['activity','↗','履歴']];
const titles={dashboard:'資産ダッシュボード',calendar:'抽選カレンダー',lotteries:'抽選管理',ledger:'購入・売却',inventory:'在庫管理',activity:'開封・店舗実績',products:'商品マスター'};
const fields={
 lotteries:[['title','抽選名','text',1],['store','店舗','text'],['status','状態','select',['応募前','応募済','当選','落選','購入済']],['deadline','応募締切','datetime-local'],['resultDate','結果発表','date'],['receiveDeadline','購入期限','date'],['receivedDate','受取日','date'],['receiptStatus','受取状況','select',['対象外','要確認','未受取','受取済み']],['memo','詳細・メモ','textarea',1]],
 purchases:[['date','購入日','date'],['store','店舗','text'],['product','商品名','text',1],['quantity','数量','number'],['price','単価','number'],['category','種別','select',['BOX','パック','カード','その他']],['inventoryAction','在庫連動','select',['在庫へ追加','記録のみ']],['memo','メモ','textarea',1]],
 sales:[['date','売却日','date'],['store','売却先','text'],['product','商品名','text',1],['quantity','数量','number'],['price','単価','number'],['fee','手数料','number'],['category','在庫種別','select',['BOX','パック','カード','その他']],['inventoryAction','在庫連動','select',['在庫から減算','記録のみ']],['memo','メモ','textarea',1]],
 boxes:[['product','BOX名','text',1],['quantity','数量','number'],['cost','取得単価','number'],['marketPrice','推定価格','number'],['store','購入店','text'],['date','取得日','date'],['memo','メモ','textarea',1]],
 packs:[['product','パック名','text',1],['quantity','数量','number'],['cost','取得単価','number'],['marketPrice','推定価格','number'],['store','購入店','text'],['date','取得日','date'],['memo','メモ','textarea',1]],
 cards:[['product','カード名','text',1],['set','収録・型番','text',1],['quantity','数量','number'],['cost','取得単価','number'],['buybackPrice','買取価格','number'],['condition','状態','select',['美品','良品','傷あり','鑑定品']],['memo','メモ','textarea',1]],
 openings:[['date','開封日','date'],['product','開封するBOX名','text',1],['quantity','開封BOX数','number'],['packProduct','残すバラパック名','text',1],['packQuantity','残すバラパック数（原価0円）','number'],['hits','主なカード','textarea',1],['estimatedValue','カード推定額','number'],['memo','メモ','textarea',1]],
 products:[['name','商品名','text',1],['category','種別','select',['BOX','パック','カード']],['code','商品コード・型番','text'],['marketPrice','参考価格','number'],['buybackPrice','買取価格','number'],['updated','価格更新日','date'],['memo','メモ','textarea',1]]
};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
function navHtml(){return nav.map(([r,i,l])=>`<a class="nav-link ${route===r?'active':''}" href="#${r}"><span class="nav-icon">${i}</span><span>${l}</span></a>`).join('')}
function metric(label,value){return`<article class="metric-card"><span class="label">${label}</span><div class="metric-value">${yen.format(value)}</div></article>`}
function empty(label){return`<div class="empty-state"><strong>まだ${label}はありません</strong>右上の「追加」から最初の記録を登録できます。</div>`}
function dashboard(){const a=assets(state);const max=Math.max(a.cards,a.boxes,a.packs,1);return`<section class="hero-card"><span class="label">推定総資産</span><div class="hero-value">${yen.format(a.total)}</div><span class="delta ${a.difference<0?'negative':''}">累計購入額との差額 ${a.difference>=0?'+':''}${yen.format(a.difference)}</span></section><div class="metric-grid">${metric('現在庫取得原価',a.inventoryCost)}${metric('カード推定資産',a.cards)}${metric('BOX推定資産',a.boxes)}${metric('バラパック推定資産',a.packs)}${metric('累計購入額',a.purchases)}${metric('売却累計',state.sales.reduce((s,x)=>s+(+x.price||0)*(x.quantity==null?1:+x.quantity||0)-(+x.fee||0),0))}</div><div class="dashboard-grid"><section><div class="section-head"><h2>資産構成</h2></div><div class="panel allocation">${[['カード',a.cards],['BOX',a.boxes],['パック',a.packs]].map(([l,v])=>`<div class="bar-row"><span>${l}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><strong>${yen.format(v)}</strong></div>`).join('')}</div></section><section><div class="section-head"><h2>次の抽選</h2></div>${list(state.lotteries.filter(x=>!['落選','購入済'].includes(x.status)).slice(0,3),'lotteries')}</section></div>`}
function list(items,type){if(!items.length)return empty(({lotteries:'抽選',purchases:'購入記録',sales:'売却記録',boxes:'BOX',packs:'パック',cards:'カード',openings:'開封記録',products:'商品'}[type]||'記録'));return`<div class="list">${items.map(x=>`<article class="list-item"><div><h3>${esc(x.title||x.product||x.name||'名称未設定')}</h3><div class="list-meta">${esc(x.store||x.set||x.category||'')}${x.date?` · ${esc(x.date)}`:''}${x.quantity?` · ${esc(x.quantity)}点`:''}</div>${x.status?`<span class="badge">${esc(x.status)}</span>`:''}</div><div><div class="amount">${x.price||x.marketPrice||x.buybackPrice?yen.format((+x.price||+x.marketPrice||+x.buybackPrice||0)*(+x.quantity||1)):''}</div><button class="danger-link" data-delete="${type}" data-id="${esc(x.id)}">削除</button></div></article>`).join('')}</div>`}
function tabs(options){return`<div class="tabs">${options.map(([k,l])=>`<button class="tab ${subtype===k?'active':''}" data-subtype="${k}">${l}</button>`).join('')}</div>`}
const receiptStatus=x=>x.receiptStatus|| (x.status==='購入済'?'受取済み':x.status==='当選'?'要確認':'対象外');
function calendar(){
 const [year,month]=calendarMonth.split('-').map(Number),first=new Date(year,month-1,1),days=new Date(year,month,0).getDate(),start=first.getDay();
 const events=new Map();const add=(date,item,label,kind)=>{if(!date||date.slice(0,7)!==calendarMonth)return;const key=date.slice(0,10);if(!events.has(key))events.set(key,[]);events.get(key).push({item,label,kind})};
 for(const x of state.lotteries){add((x.deadline||'').slice(0,10),x,'応募締切','deadline');add(x.resultDate,x,'結果','result');add(x.receiveDeadline,x,'購入期限','receipt')}
 const weekdays=['日','月','火','水','木','金','土'];
 const cells=[];for(let i=0;i<start;i++)cells.push('<div class="calendar-day muted"></div>');
 for(let day=1;day<=days;day++){const date=`${calendarMonth}-${String(day).padStart(2,'0')}`,items=events.get(date)||[],results=items.filter(x=>x.kind==='result'),count=kind=>items.filter(x=>x.kind===kind).length,statusCount=status=>results.filter(x=>x.item.status===status).length;const counts=[['win','当選',results.filter(x=>['当選','購入済'].includes(x.item.status)).length],['loss','落選',statusCount('落選')],['pending','結果待ち',results.filter(x=>!['当選','落選','購入済'].includes(x.item.status)).length],['deadline','締切',count('deadline')],['receipt','購入',count('receipt')]].filter(x=>x[2]).map(([kind,label,n])=>`<span class="calendar-count ${kind}">${label} ${n}件</span>`).join('');cells.push(`<button class="calendar-day ${selectedCalendarDate===date?'selected':''} ${today()===date?'today':''}" data-calendar-day="${date}"><strong>${day}</strong>${counts}</button>`)}
 const pending=state.lotteries.filter(x=>receiptStatus(x)==='未受取'),review=state.lotteries.filter(x=>receiptStatus(x)==='要確認');
 const selected=events.get(selectedCalendarDate)||[];const details=selected.length?selected.map(({item,label,kind})=>{const received=receiptStatus(item),status=item.status||'未設定',statusClass=status==='当選'||status==='購入済'?'win':status==='落選'?'loss':'pending';const action=status==='当選'&&received!=='受取済み'?`<button class="receipt-button" data-received-id="${esc(item.id)}">受取済みにする</button>`:'';const controls=kind==='result'?`<div class="result-controls"><button data-lottery-status="当選" data-lottery-id="${esc(item.id)}">当選</button><button data-lottery-status="落選" data-lottery-id="${esc(item.id)}">落選</button><button data-lottery-status="応募済" data-lottery-id="${esc(item.id)}">結果待ち</button></div>`:'';return`<article class="calendar-detail ${esc(kind)} status-${statusClass}"><div><b>${esc(label)} · ${esc(status)}</b><h3>${esc(item.title)}</h3><span>${esc(item.store||'')}</span><dl><div><dt>応募締切</dt><dd>${esc((item.deadline||'未設定').replace('T',' '))}</dd></div><div><dt>結果発表</dt><dd>${esc(item.resultDate||'未設定')}</dd></div><div><dt>購入期限</dt><dd>${esc(item.receiveDeadline||'未設定')}</dd></div><div><dt>受取状況</dt><dd>${esc(received)}</dd></div><div><dt>受取日</dt><dd>${esc(item.receivedDate||'未設定')}</dd></div></dl>${item.memo?`<p>${esc(item.memo)}</p>`:''}${controls}</div>${action}</article>`}).join(''):`<div class="calendar-empty">この日の予定はありません</div>`;
 return `<div class="calendar-toolbar"><button class="secondary-button compact" data-calendar-move="-1">‹ 前月</button><h2>${year}年${month}月</h2><button class="secondary-button compact" data-calendar-move="1">次月 ›</button></div>${pending.length?`<section class="pending-receipts"><b>未受取 ${pending.length}件</b><span>期限の近いものを忘れずに確認</span></section>`:''}${review.length?`<section class="pending-receipts review"><b>要確認 ${review.length}件</b><span>受取状況が未確定の当選記録</span></section>`:''}<div class="calendar-weekdays">${weekdays.map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div><section class="calendar-details"><h2>${esc(selectedCalendarDate)} の予定</h2>${details}</section>`
}
function inventory(){const options=[['boxes','未開封BOX'],['packs','バラパック'],['cards','カード'],['products','商品マスター']];const items=state[subtype]||state.boxes;return tabs(options)+list(subtype==='products'?items:items.filter(x=>Number(x.quantity)>0),subtype)}
function ledger(){const options=[['purchases','購入・支出'],['sales','売却']];if(!['purchases','sales'].includes(subtype))subtype='purchases';return tabs(options)+list(state[subtype],subtype)}
function activity(){const stats=storeStats(state);const options=[['openings','開封記録'],['stores','店舗別実績']];if(!['openings','stores'].includes(subtype))subtype='openings';if(subtype==='openings')return tabs(options)+list(state.openings,'openings');return tabs(options)+(stats.length?`<div class="list">${stats.map(x=>`<article class="list-item"><div><h3>${esc(x.store)}</h3><div class="list-meta">購入 ${x.purchases}件 · 売却 ${x.sales}件</div></div><div class="amount">支出 ${yen.format(x.spent)}<br><span class="list-meta">売却 ${yen.format(x.revenue)}</span></div></article>`).join('')}</div>`:empty('店舗実績'))}
function render(){if(!titles[route])route='dashboard';document.querySelector('#page-title').textContent=titles[route];document.querySelector('#desktop-nav').innerHTML=navHtml();document.querySelector('#mobile-nav').innerHTML=navHtml();const views={dashboard,calendar,lotteries:()=>list(state.lotteries,'lotteries'),ledger,inventory,activity};document.querySelector('#view').innerHTML=views[route]();document.querySelector('[data-action="add-current"]').hidden=route==='dashboard'||(route==='activity'&&subtype==='stores')}
function openForm(type){if(type==='calendar')type='lotteries';if(type==='ledger')type=subtype==='sales'?'sales':'purchases';if(type==='inventory')type=['boxes','packs','cards','products'].includes(subtype)?subtype:'boxes';if(type==='activity')type='openings';const f=fields[type];if(!f)return;document.querySelector('#entry-form').dataset.type=type;document.querySelector('#form-title').textContent=`${({lotteries:'抽選',purchases:'購入',sales:'売却',boxes:'BOX',packs:'パック',cards:'カード',openings:'開封',products:'商品'}[type])}を追加`;document.querySelector('#form-fields').innerHTML=f.map(([name,label,kind,extra])=>{const full=extra===1?' full':'';if(kind==='select')return`<div class="field${full}"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${extra.map(o=>`<option>${o}</option>`).join('')}</select></div>`;if(kind==='textarea')return`<div class="field${full}"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}"></textarea></div>`;return`<div class="field${full}"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${kind}" ${kind==='number'?'min="0" inputmode="numeric"':''} ${name==='quantity'?'value="1"':''} ${name==='date'?'value="'+today()+'"':''} ${['title','product','name'].includes(name)?'required':''}></div>`}).join('');document.querySelector('#entry-dialog').showModal()}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function readFile(input){const file=input.files[0];if(!file)return null;return file.text()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='add-current')openForm(route);if(act==='close-dialog')document.querySelector('#entry-dialog').close();if(act==='open-settings')document.querySelector('#settings-dialog').showModal();if(act==='close-settings')document.querySelector('#settings-dialog').close();if(act==='export-json')download(`toreca-vault-${today()}.json`,backup(state))}const move=e.target.closest('[data-calendar-move]');if(move){const [y,m]=calendarMonth.split('-').map(Number),d=new Date(y,m-1+Number(move.dataset.calendarMove),1);calendarMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;selectedCalendarDate=`${calendarMonth}-01`;render()}const day=e.target.closest('[data-calendar-day]');if(day){selectedCalendarDate=day.dataset.calendarDay;render();requestAnimationFrame(()=>document.querySelector('.calendar-details')?.scrollIntoView({behavior:'smooth',block:'nearest'}))}const result=e.target.closest('[data-lottery-status]');if(result){const item=state.lotteries.find(x=>x.id===result.dataset.lotteryId);if(item){item.status=result.dataset.lotteryStatus;item.receiptStatus=item.status==='当選'?'未受取':'対象外';if(item.status!=='購入済')item.receivedDate='';save(state);render();toast(`${item.status}に変更しました`)}}const received=e.target.closest('[data-received-id]');if(received){const item=state.lotteries.find(x=>x.id===received.dataset.receivedId);if(item){item.receiptStatus='受取済み';item.receivedDate=today();item.status='購入済';save(state);render();toast('受取済みにしました')}}const tab=e.target.closest('[data-subtype]');if(tab){subtype=tab.dataset.subtype;render()}const del=e.target.closest('[data-delete]');if(del&&confirm('この記録を削除しますか？')){state[del.dataset.delete]=state[del.dataset.delete].filter(x=>x.id!==del.dataset.id);save(state);render();toast('削除しました')}});
document.querySelector('#entry-form').addEventListener('submit',e=>{e.preventDefault();const type=e.currentTarget.dataset.type;const data=Object.fromEntries(new FormData(e.currentTarget));for(const k of ['quantity','packQuantity','price','cost','marketPrice','buybackPrice','fee','estimatedValue'])if(k in data)data[k]=Number(data[k])||0;data.id=id();data.createdAt=new Date().toISOString();try{if(type==='purchases')state=applyPurchase(state,data);else if(type==='sales')state=applySale(state,data);else if(type==='openings')state=applyOpening(state,data);else state[type].unshift(data);save(state);document.querySelector('#entry-dialog').close();render();toast('保存しました')}catch(err){alert(err.message)}});
document.querySelector('#restore-input').addEventListener('change',async e=>{try{const raw=await readFile(e.target);if(!raw)return;if(!confirm('現在のデータをバックアップ内容で置き換えますか？'))return;state=restore(raw);render();toast('復元しました')}catch(err){alert(err.message)}finally{e.target.value=''}});
document.querySelector('#legacy-input').addEventListener('change',async e=>{try{const raw=await readFile(e.target);if(!raw)return;const result=importLegacy(JSON.parse(raw));if(!confirm(`${result.count}件を現在のデータに追加しますか？`))return;state=merge(state,result.state);render();toast(`${result.count}件を取り込みました`)}catch(err){alert(`インポート失敗: ${err.message}`)}finally{e.target.value=''}});
addEventListener('hashchange',()=>{route=location.hash.slice(1)||'dashboard';subtype=route==='inventory'?'boxes':route==='ledger'?'purchases':route==='activity'?'openings':subtype;render()});
document.querySelector('#today-label').textContent=dateFmt.format(new Date());render();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
