import{load,save as saveLocal,backup,restore,merge}from'./storage.js';
import{getSyncConfig,setSyncConfig,clearSyncConfig,pullRemote,pushRemote}from'./remote-sync.js';
import{assets,storeStats}from'./calculations.js';
import{id,importLegacy}from'./schema.js';
import{applyPurchase,applySale,applyOpening}from'./inventory.js';

let state=load(),remoteRevision='',remoteSaveTimer=null,remoteSaving=false;const initialHash=location.hash.slice(1).split('/');let route=initialHash[0]||'dashboard';let subtype=route==='inventory'&&['boxes','packs','cards'].includes(initialHash[1])?initialHash[1]:route==='ledger'&&initialHash[1]?initialHash[1]:'purchases';let calendarMonth=(new Date()).toISOString().slice(0,7);let selectedCalendarDate=(new Date()).toISOString().slice(0,10),reviewExpanded=false;
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat('ja-JP',{month:'short',day:'numeric',weekday:'short'});
const nav=[['dashboard','⌂','資産'],['calendar','□','予定'],['ledger','¥','収支'],['activity','↗','履歴']];
const titles={dashboard:'資産ダッシュボード',calendar:'予定カレンダー',lotteries:'予定管理',ledger:'月別収支',inventory:'在庫詳細',activity:'取引履歴',products:'商品マスター'};
const fields={
 lotteries:[['title','抽選名','text',1],['store','店舗','text'],['status','状態','select',['応募前','応募済','当選','落選','購入済']],['deadline','応募締切','datetime-local'],['resultDate','結果発表','date'],['receiveDeadline','購入期限','date'],['receivedDate','受取日','date'],['receiptStatus','受取状況','select',['対象外','要確認','未受取','受取済み']],['memo','詳細・メモ','textarea',1]],
 purchases:[['date','購入日','date'],['store','店舗','text'],['product','商品名','text',1],['quantity','数量','number'],['price','単価','number'],['category','種別','select',['BOX','パック','カード','その他']],['inventoryAction','在庫連動','select',['在庫へ追加','記録のみ']],['memo','メモ','textarea',1]],
 sales:[['date','売却日','date'],['store','売却先','text'],['product','商品名','text',1],['quantity','数量','number'],['price','単価','number'],['fee','手数料','number'],['category','在庫種別','select',['BOX','パック','カード','その他']],['inventoryAction','在庫連動','select',['在庫から減算','記録のみ']],['memo','メモ','textarea',1]],
 boxes:[['product','BOX名','text',1],['quantity','数量','number'],['cost','取得単価','number'],['marketPrice','推定価格','number'],['store','購入店','text'],['date','取得日','date'],['memo','メモ','textarea',1]],
 packs:[['product','パック名','text',1],['quantity','数量','number'],['cost','取得単価','number'],['marketPrice','推定価格','number'],['store','購入店','text'],['date','取得日','date'],['memo','メモ','textarea',1]],
 cards:[['product','カード名','text',1],['set','収録・型番','text',1],['quantity','数量','number'],['cost','取得単価','number'],['buybackPrice','買取価格','number'],['condition','状態','select',['美品','良品','傷あり','鑑定品']],['memo','メモ','textarea',1]],
 openings:[['date','開封日','date'],['product','開封するBOX名','text',1],['quantity','開封BOX数','number'],['packProduct','残すバラパック名','text',1],['packQuantity','残すバラパック数（原価0円）','number'],['hits','主なカード','textarea',1],['estimatedValue','カード推定額','number'],['memo','メモ','textarea',1]],
 products:[['name','商品名','text',1],['category','種別','select',['BOX','パック','カード']],['code','商品コード・型番','text'],['marketPrice','参考価格','number'],['buybackPrice','買取価格','number'],['updated','価格更新日','date'],['memo','メモ','textarea',1]]
};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
function setSyncStatus(message,kind=''){const el=document.querySelector('#sync-status');if(!el)return;el.textContent=message;el.className=`notice ${kind}`.trim()}
function fillSyncSettings(){const c=getSyncConfig(),url=document.querySelector('#sync-url'),token=document.querySelector('#sync-token');if(url)url.value=c.url||'';if(token)token.value=c.token||'';setSyncStatus(c.url?'接続設定済み':'未接続',c.url?'success':'')}
async function pullAndApply(showToast=false){const remote=await pullRemote();if(!remote)return false;remoteRevision=remote.revision;state=saveLocal(remote.data,{touch:false});render();setSyncStatus(`同期済み ${new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}`,'success');if(showToast)toast('最新データへ同期しました');return true}
async function flushRemoteSave(){if(remoteSaving)return;remoteSaving=true;try{const result=await pushRemote(state,remoteRevision);if(result.skipped)return;if(result.ok){remoteRevision=result.revision;setSyncStatus('変更を同期しました','success')}else{remoteRevision=result.revision;state=saveLocal(result.data,{touch:false});render();setSyncStatus('別の更新を優先して再読込しました','warning');toast('新しいDriveデータを再読込しました')}}catch(err){console.warn('自動同期に失敗しました',err);setSyncStatus(`同期失敗: ${err.message}`,'warning')}finally{remoteSaving=false}}
function scheduleRemoteSave(){if(!getSyncConfig().url)return;clearTimeout(remoteSaveTimer);remoteSaveTimer=setTimeout(flushRemoteSave,800)}
function save(next,options){const saved=saveLocal(next,options);if(options?.remote!==false)scheduleRemoteSave();return saved}
function navHtml(){return nav.map(([r,i,l])=>`<a class="nav-link ${route===r?'active':''}" href="#${r}"><span class="nav-icon">${i}</span><span>${l}</span></a>`).join('')}
function metric(label,value,href=''){const body=`<span class="label">${label}</span><div class="metric-value">${yen.format(value)}</div>`;return href?`<a class="metric-card tappable" href="${href}">${body}<small>詳細を見る ›</small></a>`:`<article class="metric-card">${body}</article>`}
function empty(label){return`<div class="empty-state"><strong>まだ${label}はありません</strong>右上の「追加」から最初の記録を登録できます。</div>`}
const saleRevenue=x=>(+x.price||0)*(x.quantity==null?1:+x.quantity||0)-(+x.fee||0);
for(const item of [...state.purchases,...state.sales]){const category=String(item.category||'').trim();if(['シングル','シングルカード'].includes(category))item.category='カード';else if(['ボックス','未開封BOX'].includes(category))item.category='BOX';else if(category==='バラパック')item.category='パック'}
const realizedProfit=()=>state.sales.reduce((s,x)=>s+saleRevenue(x)-(+x.acquisitionCost||0),0);
function dashboard(){const a=assets(state),max=Math.max(a.cards,a.boxes,a.packs,1),profit=realizedProfit();return`<div class="hero-grid"><section class="hero-card"><span class="label">推定総資産</span><div class="hero-value">${yen.format(a.total)}</div><span class="delta ${a.difference<0?'negative':''}">累計購入額との差額 ${a.difference>=0?'+':''}${yen.format(a.difference)}</span></section><section class="hero-card profit"><span class="label">実現損益</span><div class="hero-value">${profit>=0?'+':''}${yen.format(profit)}</div><span class="delta ${profit<0?'negative':''}">売却済みのみ</span></section></div><div class="metric-grid">${metric('現在庫取得原価',a.inventoryCost)}${metric('カード推定資産',a.cards,'#inventory/cards')}${metric('BOX推定資産',a.boxes,'#inventory/boxes')}${metric('バラパック推定資産',a.packs,'#inventory/packs')}${metric('累計購入額',a.purchases)}${metric('売却累計',state.sales.reduce((s,x)=>s+saleRevenue(x),0))}</div><section><div class="section-head"><h2>資産構成</h2><span>項目をタップして在庫へ</span></div><div class="panel allocation">${[['カード',a.cards,'cards'],['BOX',a.boxes,'boxes'],['パック',a.packs,'packs']].map(([l,v,k])=>`<a class="bar-row" href="#inventory/${k}"><span>${l}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><strong>${yen.format(v)}</strong></a>`).join('')}</div></section>`}
function list(items,type){if(!items.length)return empty(({lotteries:'抽選',purchases:'購入記録',sales:'売却記録',boxes:'BOX',packs:'パック',cards:'カード',openings:'開封記録',products:'商品'}[type]||'記録'));return`<div class="list">${items.map(x=>`<article class="list-item"><div><h3>${esc(x.title||x.product||x.name||'名称未設定')}</h3><div class="list-meta">${esc(x.store||x.set||x.category||'')}${x.date?` · ${esc(x.date)}`:''}${x.quantity?` · ${esc(x.quantity)}点`:''}</div>${x.status?`<span class="badge">${esc(x.status)}</span>`:''}</div><div><div class="amount">${x.price||x.marketPrice||x.buybackPrice?yen.format((+x.price||+x.marketPrice||+x.buybackPrice||0)*(+x.quantity||1)):''}</div><button class="danger-link" data-delete="${type}" data-id="${esc(x.id)}">削除</button></div></article>`).join('')}</div>`}
function tabs(options){return`<div class="tabs">${options.map(([k,l])=>`<button class="tab ${subtype===k?'active':''}" data-subtype="${k}">${l}</button>`).join('')}</div>`}
const receiptStatus=x=>x.receiptStatus==='未受取'&&!x.receiveDeadline&&!x.receivedDate?'要確認':x.receiptStatus|| (x.status==='購入済'?'受取済み':x.status==='当選'?'要確認':'対象外');
function calendar(){
 const [year,month]=calendarMonth.split('-').map(Number),first=new Date(year,month-1,1),days=new Date(year,month,0).getDate(),start=first.getDay();
 const events=new Map();const add=(date,item,label,kind)=>{if(!date||date.slice(0,7)!==calendarMonth)return;const key=date.slice(0,10);if(!events.has(key))events.set(key,[]);events.get(key).push({item,label,kind})};
 for(const x of state.lotteries){add((x.deadline||'').slice(0,10),x,'応募締切','deadline');add(x.resultDate,x,'結果','result');add(x.receiveDeadline,x,'購入期限','receipt')}
 const weekdays=['日','月','火','水','木','金','土'];
 const cells=[];for(let i=0;i<start;i++)cells.push('<div class="calendar-day muted"></div>');
 for(let day=1;day<=days;day++){const date=`${calendarMonth}-${String(day).padStart(2,'0')}`,items=events.get(date)||[],results=items.filter(x=>x.kind==='result'),count=kind=>items.filter(x=>x.kind===kind).length,statusCount=status=>results.filter(x=>x.item.status===status).length;const counts=[['win','当選',results.filter(x=>['当選','購入済'].includes(x.item.status)).length],['loss','落選',statusCount('落選')],['pending','結果待ち',results.filter(x=>!['当選','落選','購入済'].includes(x.item.status)).length],['deadline','締切',count('deadline')],['receipt','購入',count('receipt')]].filter(x=>x[2]).map(([kind,label,n])=>`<span class="calendar-count ${kind}">${label} ${n}件</span>`).join('');cells.push(`<button class="calendar-day ${selectedCalendarDate===date?'selected':''} ${today()===date?'today':''}" data-calendar-day="${date}"><strong>${day}</strong>${counts}</button>`)}
 const pending=state.lotteries.filter(x=>receiptStatus(x)==='未受取'),review=state.lotteries.filter(x=>receiptStatus(x)==='要確認');
 const selected=events.get(selectedCalendarDate)||[];const details=selected.length?selected.map(({item,label,kind})=>{const received=receiptStatus(item),status=item.status||'未設定',statusClass=status==='当選'||status==='購入済'?'win':status==='落選'?'loss':'pending';const action=status==='当選'&&received!=='受取済み'?`<button class="receipt-button" data-received-id="${esc(item.id)}">受取済みにする</button>`:'';const controls=kind==='result'&&!['当選','落選','購入済'].includes(status)?`<div class="result-controls"><button data-lottery-status="当選" data-lottery-id="${esc(item.id)}">当選</button><button data-lottery-status="落選" data-lottery-id="${esc(item.id)}">落選</button></div>`:'';return`<article class="calendar-detail ${esc(kind)} status-${statusClass}"><div><b>${esc(label)} · ${esc(status)}</b><h3>${esc(item.title)}</h3><span>${esc(item.store||'')}</span><dl><div><dt>応募締切</dt><dd>${esc((item.deadline||'未設定').replace('T',' '))}</dd></div><div><dt>結果発表</dt><dd>${esc(item.resultDate||'未設定')}</dd></div><div><dt>購入期限</dt><dd>${esc(item.receiveDeadline||'未設定')}</dd></div><div><dt>受取状況</dt><dd>${esc(received)}</dd></div><div><dt>受取日</dt><dd>${esc(item.receivedDate||'未設定')}</dd></div></dl>${item.memo?`<p>${esc(item.memo)}</p>`:''}${controls}</div>${action}</article>`}).join(''):`<div class="calendar-empty">この日の予定はありません</div>`;
 const reviewDetails=reviewExpanded&&review.length?`<section class="review-details"><div class="section-head"><h2>要確認の詳細</h2><span>${review.length}件</span></div><div class="list">${review.map(item=>`<article class="calendar-detail status-pending"><div><b>${esc(item.status||'状態未設定')} · ${esc(receiptStatus(item))}</b><h3>${esc(item.title||'名称未設定')}</h3><span>${esc(item.store||'店舗未設定')}</span><dl><div><dt>結果発表</dt><dd>${esc(item.resultDate||'未設定')}</dd></div><div><dt>購入期限</dt><dd>${esc(item.receiveDeadline||item.purchaseDeadline||'未設定')}</dd></div><div><dt>受取日</dt><dd>${esc(item.receivedDate||'未設定')}</dd></div></dl>${item.memo?`<p>${esc(item.memo)}</p>`:''}</div></article>`).join('')}</div></section>`:'';
 return `<div class="calendar-toolbar"><button class="secondary-button compact" data-calendar-move="-1">‹ 前月</button><h2>${year}年${month}月</h2><button class="secondary-button compact" data-calendar-move="1">次月 ›</button></div>${pending.length?`<section class="pending-receipts"><b>未受取 ${pending.length}件</b><span>期限の近いものを忘れずに確認</span></section>`:''}${review.length?`<button class="pending-receipts review review-toggle" data-show-review aria-expanded="${reviewExpanded}"><b>要確認 ${review.length}件</b><span>タップして詳細を${reviewExpanded?'閉じる':'表示'}</span></button>`:''}${reviewDetails}<div class="calendar-weekdays">${weekdays.map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div><section class="calendar-details"><h2>${esc(selectedCalendarDate)} の予定</h2>${details}</section>`
}
function inventory(){const options=[['boxes','未開封BOX'],['packs','バラパック'],['cards','カード']];const items=(state[subtype]||state.boxes).filter(x=>Number(x.quantity)>0);return tabs(options)+list(items,subtype)}
function ledger(){const months=[...new Set([...state.purchases,...state.sales].map(x=>(x.date||'').slice(0,7)).filter(Boolean))].sort().reverse(),month=subtype?.match(/^\d{4}-\d{2}$/)?subtype:months[0]||today().slice(0,7),p=state.purchases.filter(x=>(x.date||'').startsWith(month)),s=state.sales.filter(x=>(x.date||'').startsWith(month)),spent=p.reduce((n,x)=>n+(+x.total||(+x.price||0)*(+x.quantity||1)),0),revenue=s.reduce((n,x)=>n+saleRevenue(x),0),cost=s.reduce((n,x)=>n+(+x.acquisitionCost||0),0),profit=revenue-cost,recovery=cost?`${Math.round(revenue/cost*100)}%`:'—',categories=['BOX','カード','パック','その他'].map(category=>{const cp=p.filter(x=>(x.category||'その他')===category),cs=s.filter(x=>(x.category||'その他')===category);return[category,cp.reduce((n,x)=>n+(+x.total||(+x.price||0)*(+x.quantity||1)),0),cs.reduce((n,x)=>n+saleRevenue(x),0)]}),rows=[...p.map(x=>({...x,_kind:'購入',_collection:'purchases'})),...s.map(x=>({...x,_kind:'売却',_collection:'sales'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||''));return`<div class="month-tabs">${months.map(m=>`<button class="tab ${m===month?'active':''}" data-month="${m}">${m}</button>`).join('')}</div><div class="metric-grid">${metric('購入額',spent)}${metric('売却額',revenue)}${metric('実現損益',profit)}<article class="metric-card"><span class="label">回収率</span><div class="metric-value">${recovery}</div></article></div><section><div class="section-head"><h2>種別内訳</h2></div><div class="panel finance-breakdown">${categories.map(([c,buy,sale])=>`<div><b>${c}</b><span>購入 ${yen.format(buy)}</span><span>売却 ${yen.format(sale)}</span></div>`).join('')}</div></section>${rows.length?`<div class="list">${rows.map(x=>`<article class="list-item"><div><h3>${esc(x.product||'名称未設定')}</h3><div class="list-meta">${esc(x._kind)} · ${esc(x.store||'')}${x.date?` · ${esc(x.date)}`:''}${x.quantity?` · ${esc(x.quantity)}点`:''}</div></div><div><div class="amount">${yen.format(x._kind==='売却'?saleRevenue(x):(+x.total||(+x.price||0)*(+x.quantity||1)))}</div><button class="danger-link" data-delete="${x._collection}" data-id="${esc(x.id)}">削除</button></div></article>`).join('')}</div>`:empty('収支記録')}`}
function activity(){const all=[...state.purchases.map(x=>({...x,_kind:'購入'})),...state.sales.map(x=>({...x,_kind:'売却'})),...state.openings.map(x=>({...x,_kind:'開封'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||''));return all.length?`<div class="list">${all.map(x=>`<article class="list-item"><div><h3>${esc(x.product||x.title)}</h3><div class="list-meta">${esc(x._kind)} · ${esc(x.store||'')}${x.date?` · ${esc(x.date)}`:''}</div></div><div class="amount">${x.price?yen.format((+x.price||0)*(+x.quantity||1)):''}</div></article>`).join('')}</div>`:empty('履歴')}
function render(){if(!titles[route])route='dashboard';document.querySelector('#page-title').textContent=titles[route];document.querySelector('#desktop-nav').innerHTML=navHtml();document.querySelector('#mobile-nav').innerHTML=navHtml();const views={dashboard,calendar,lotteries:()=>list(state.lotteries,'lotteries'),ledger,inventory,activity};document.querySelector('#view').innerHTML=views[route]();document.querySelector('[data-action="add-current"]').hidden=route==='dashboard'||(route==='activity'&&subtype==='stores')}
function openForm(type){if(type==='calendar')type='lotteries';if(type==='ledger')type=subtype==='sales'?'sales':'purchases';if(type==='inventory')type=['boxes','packs','cards','products'].includes(subtype)?subtype:'boxes';if(type==='activity')type='openings';const f=fields[type];if(!f)return;document.querySelector('#entry-form').dataset.type=type;document.querySelector('#form-title').textContent=`${({lotteries:'抽選',purchases:'購入',sales:'売却',boxes:'BOX',packs:'パック',cards:'カード',openings:'開封',products:'商品'}[type])}を追加`;document.querySelector('#form-fields').innerHTML=f.map(([name,label,kind,extra])=>{const full=extra===1?' full':'';if(kind==='select')return`<div class="field${full}"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${extra.map(o=>`<option>${o}</option>`).join('')}</select></div>`;if(kind==='textarea')return`<div class="field${full}"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}"></textarea></div>`;return`<div class="field${full}"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${kind}" ${kind==='number'?'min="0" inputmode="numeric"':''} ${name==='quantity'?'value="1"':''} ${name==='date'?'value="'+today()+'"':''} ${['title','product','name'].includes(name)?'required':''}></div>`}).join('');document.querySelector('#entry-dialog').showModal()}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function readFile(input){const file=input.files[0];if(!file)return null;return file.text()}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='add-current')openForm(route);if(act==='close-dialog')document.querySelector('#entry-dialog').close();if(act==='open-settings'){document.querySelector('#settings-dialog').showModal();fillSyncSettings()}if(act==='close-settings')document.querySelector('#settings-dialog').close();if(act==='export-json')download(`toreca-vault-${today()}.json`,backup(state));if(act==='connect-sync'){try{e.preventDefault();setSyncConfig(document.querySelector('#sync-url').value,document.querySelector('#sync-token').value);setSyncStatus('接続中…');await pullAndApply(true)}catch(err){setSyncStatus(err.message,'warning')}}if(act==='sync-now'){try{e.preventDefault();setSyncStatus('同期中…');await pullAndApply(true)}catch(err){setSyncStatus(err.message,'warning')}}if(act==='disconnect-sync'){e.preventDefault();clearSyncConfig();remoteRevision='';fillSyncSettings();toast('自動同期を解除しました')}}const reviewToggle=e.target.closest('[data-show-review]');if(reviewToggle){reviewExpanded=!reviewExpanded;render();if(reviewExpanded)requestAnimationFrame(()=>document.querySelector('.review-details')?.scrollIntoView({behavior:'smooth',block:'nearest'}))}const month=e.target.closest('[data-month]');if(month){subtype=month.dataset.month;render()}const move=e.target.closest('[data-calendar-move]');if(move){const [y,m]=calendarMonth.split('-').map(Number),d=new Date(y,m-1+Number(move.dataset.calendarMove),1);calendarMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;selectedCalendarDate=`${calendarMonth}-01`;render()}const day=e.target.closest('[data-calendar-day]');if(day){selectedCalendarDate=day.dataset.calendarDay;render();requestAnimationFrame(()=>document.querySelector('.calendar-details')?.scrollIntoView({behavior:'smooth',block:'nearest'}))}const result=e.target.closest('[data-lottery-status]');if(result){const item=state.lotteries.find(x=>x.id===result.dataset.lotteryId);if(item){item.status=result.dataset.lotteryStatus;item.receiptStatus=item.status==='当選'?'未受取':'対象外';if(item.status!=='購入済')item.receivedDate='';save(state);render();toast(`${item.status}に変更しました`)}}const received=e.target.closest('[data-received-id]');if(received){const item=state.lotteries.find(x=>x.id===received.dataset.receivedId);if(item){item.receiptStatus='受取済み';item.receivedDate=today();item.status='購入済';save(state);render();toast('受取済みにしました')}}const tab=e.target.closest('[data-subtype]');if(tab){subtype=tab.dataset.subtype;render()}const del=e.target.closest('[data-delete]');if(del&&confirm('この記録を削除しますか？')){state[del.dataset.delete]=state[del.dataset.delete].filter(x=>x.id!==del.dataset.id);save(state);render();toast('削除しました')}});
document.querySelector('#entry-form').addEventListener('submit',e=>{e.preventDefault();const type=e.currentTarget.dataset.type;const data=Object.fromEntries(new FormData(e.currentTarget));for(const k of ['quantity','packQuantity','price','cost','marketPrice','buybackPrice','fee','estimatedValue'])if(k in data)data[k]=Number(data[k])||0;data.id=id();data.createdAt=new Date().toISOString();try{if(type==='purchases')state=applyPurchase(state,data);else if(type==='sales')state=applySale(state,data);else if(type==='openings')state=applyOpening(state,data);else state[type].unshift(data);save(state);document.querySelector('#entry-dialog').close();render();toast('保存しました')}catch(err){alert(err.message)}});
document.querySelector('#restore-input').addEventListener('change',async e=>{try{const raw=await readFile(e.target);if(!raw)return;if(!confirm('現在のデータをバックアップ内容で置き換えますか？'))return;state=restore(raw);render();toast('復元しました')}catch(err){alert(err.message)}finally{e.target.value=''}});
document.querySelector('#legacy-input').addEventListener('change',async e=>{try{const raw=await readFile(e.target);if(!raw)return;const result=importLegacy(JSON.parse(raw));if(!confirm(`${result.count}件を現在のデータに追加しますか？`))return;state=merge(state,result.state);render();toast(`${result.count}件を取り込みました`)}catch(err){alert(`インポート失敗: ${err.message}`)}finally{e.target.value=''}});
addEventListener('hashchange',()=>{const [next,param]=location.hash.slice(1).split('/');route=next||'dashboard';if(route==='inventory')subtype=['boxes','packs','cards'].includes(param)?param:'boxes';if(route==='ledger'&&param)subtype=param;render()});
document.querySelector('#today-label').textContent=dateFmt.format(new Date());render();
if(getSyncConfig().url)pullAndApply().catch(err=>console.warn('起動時同期に失敗しました',err));
async function syncPublishedMarket(){
 try{
  const response=await fetch('./market-update.json',{cache:'no-store'});if(!response.ok)return;
  const update=await response.json(),prices=update.boxPrices||{},excluded=new Set(update.excludeInventoryIds||[]);
  const before=JSON.stringify(state.boxes);
  state.boxes=state.boxes.filter(x=>!excluded.has(x.id)).map(x=>{if(!Object.hasOwn(prices,x.product))return x;const price=Number(prices[x.product].price),history=[...(x.marketHistory||[])];if(!history.some(h=>h.date===update.checkedAt&&h.value===price))history.push({date:update.checkedAt,value:price});return{...x,marketPrice:price,marketCheckedAt:update.checkedAt,marketSource:prices[x.product].source,marketHistory:history.slice(-400)}});
  if(before!==JSON.stringify(state.boxes)){save(state);render();toast(`BOX相場を${update.checkedAt}版へ更新しました`)}
 }catch(err){console.warn('公開相場を読み込めません',err)}
}
syncPublishedMarket();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
