import test from'node:test';import assert from'node:assert/strict';import{emptyV2}from'../v2/core.js';import{matchLottery,mergeLotteryMail,applyMarketFetch,recordAutomationHealth,runMarketBatch,runLotteryBatch}from'../v2/automation.js';
test('same application id duplicates are ignored, not review',()=>{const s=emptyV2();s.lotteries=[{id:'a',applicationId:'104'},{id:'b',applicationId:'104'}];assert.equal(matchLottery(s.lotteries,{applicationId:'104'}).kind,'duplicate');assert.equal(mergeLotteryMail(s,{applicationId:'104'}).outcome,'duplicate')});
test('truly ambiguous fallback goes to review',()=>{const s=emptyV2();s.lotteries=[{id:'a',store:'X',product:'Y'},{id:'b',store:'X',product:'Y'}];assert.equal(matchLottery(s.lotteries,{store:'X',product:'Y'}).kind,'review')});
test('market fetch failure preserves prior quote',()=>{const s=emptyV2();s.marketQuotes=[{productKey:'p',condition:'あり',price:100,history:[]}];const r=applyMarketFetch(s,{productKey:'p',product:'P',category:'BOX',condition:'あり'},{ok:false});assert.equal(r.outcome,'preserved');assert.equal(r.state.marketQuotes[0].price,100)});
test('market success updates quote and history',()=>{const s=emptyV2();const r=applyMarketFetch(s,{productKey:'p',product:'P',category:'BOX',condition:'あり'},{ok:true,price:120,checkedAt:'2026-09-19',source:'S'});assert.equal(r.state.marketQuotes[0].price,120);assert.equal(r.state.marketQuotes[0].history.length,1)});
test('health retains last success across failure',()=>{let s=recordAutomationHealth(emptyV2(),'market',{ok:true,at:'a',externalFetchCount:2});s=recordAutomationHealth(s,'market',{ok:false,at:'b',error:'x'});assert.equal(s.automation.health.market.lastSuccessAt,'a');assert.equal(s.automation.health.market.lastFailureAt,'b')});

test('market batch preserves failed quote and records health',()=>{const s=emptyV2();s.marketQuotes=[{productKey:'p',condition:'あり',price:100,history:[]}];const r=runMarketBatch(s,[{productKey:'p',product:'P',category:'BOX',condition:'あり'}],()=>({ok:false}),'t');assert.equal(r.preserved,1);assert.equal(r.state.marketQuotes[0].price,100);assert.equal(r.state.automation.health.market.ok,false)});
test('lottery batch counts duplicate without review',()=>{const s=emptyV2();s.lotteries=[{id:'a',applicationId:'104'},{id:'b',applicationId:'104'}];const r=runLotteryBatch(s,[{applicationId:'104'}],'t');assert.equal(r.duplicate,1);assert.equal(r.review,0);assert.equal(r.state.automation.health.lottery.ok,true)});

test('lottery mail without stable id is review and cannot create a record',()=>{const s=emptyV2();const r=mergeLotteryMail(s,{store:'X',product:'Y'});assert.equal(r.outcome,'review');assert.equal(r.state.lotteries.length,0)});
test('lottery batch rejects non-array input',()=>{assert.throws(()=>runLotteryBatch(emptyV2(),null,'t'),/array/)});
