import test from'node:test';import assert from'node:assert/strict';import{emptyV2,applyTransaction,setCardIdentity,realizedProfit,positiveMarketTargets}from'../v2/core.js';
const buy=(id,date,price,condition='あり',quantity=1)=>({id,type:'purchase',date,product:'X',productKey:'x',category:'BOX',condition,quantity,price});
const sale=(id,quantity=1,condition='あり',price=0)=>({id,type:'sale',date:'2026-09-19',product:'X',productKey:'x',category:'BOX',condition,quantity,price});
test('purchase increases stock and duplicate mutation is idempotent',()=>{let s=applyTransaction(emptyV2(),buy('p1','2026-01-01',100),'m1');assert.equal(s.inventoryLots[0].quantity,1);const again=applyTransaction(s,buy('p2','2026-01-02',200),'m1');assert.deepEqual(again,s)});
test('condition separates BOX stock',()=>{let s=applyTransaction(emptyV2(),buy('p1','2026-01-01',100,'あり'),'m1');s=applyTransaction(s,buy('p2','2026-01-01',200,'なし'),'m2');assert.throws(()=>applyTransaction(s,sale('s1',2,'あり',500),'m3'),/在庫不足/)});
test('sale uses FIFO and partial quantity remains',()=>{let s=applyTransaction(emptyV2(),buy('p1','2026-01-01',100,'あり',1),'m1');s=applyTransaction(s,buy('p2','2026-01-02',200,'あり',2),'m2');s=applyTransaction(s,sale('s1',2,'あり',300),'m3');assert.equal(s.transactions.at(-1).acquisitionCost,300);assert.equal(s.inventoryLots.reduce((n,x)=>n+x.quantity,0),1);assert.equal(realizedProfit(s),300)});
test('failed sale changes nothing',()=>{let s=applyTransaction(emptyV2(),buy('p1','2026-01-01',100),'m1');const before=structuredClone(s);assert.throws(()=>applyTransaction(s,sale('s1',2,'あり',300),'m2'),/在庫不足/);assert.deepEqual(s,before)});
test('market targets dedupe product and condition',()=>{let s=applyTransaction(emptyV2(),buy('p1','2026-01-01',100),'m1');s=applyTransaction(s,buy('p2','2026-01-02',200),'m2');assert.equal(positiveMarketTargets(s).length,1)});

test('unknown lot cost stays pending on sale',()=>{let s=emptyV2();s=applyTransaction(s,{id:'u1',type:'purchase',date:'2026-09-19',product:'U',category:'カード',condition:'良品',quantity:1},'mu1');s=applyTransaction(s,{id:'u2',type:'sale',date:'2026-09-19',product:'U',category:'カード',condition:'良品',quantity:1,price:500},'mu2');assert.equal(s.transactions.at(-1).acquisitionCost,null);assert.equal(realizedProfit(s),0)});
test('zero and negative quantities are rejected',()=>{const s=emptyV2();for(const quantity of [0,-1,1.5])assert.throws(()=>applyTransaction(s,{id:'bad'+quantity,type:'purchase',product:'X',category:'BOX',condition:'あり',quantity,price:100},'m'+quantity),/quantity/)});
test('opening consumes the stated category instead of forcing BOX',()=>{let s=emptyV2();s=applyTransaction(s,{id:'pk1',type:'purchase',product:'Pack',category:'パック',condition:'',quantity:1,price:100},'mp1');s=applyTransaction(s,{id:'op1',type:'opening',product:'Pack',category:'パック',condition:'',quantity:1},'mo1');assert.equal(s.inventoryLots.length,0)});

test('special BOX can use unopened condition',()=>{let s=emptyV2();s=applyTransaction(s,{id:'sp1',type:'purchase',product:'スペシャルBOX',category:'BOX',condition:'未開封',quantity:1,price:100},'msp1');assert.equal(s.inventoryLots[0].condition,'未開封')});

test('productless transaction is rejected without changing state',()=>{const s=emptyV2(),before=structuredClone(s);assert.throws(()=>applyTransaction(s,{id:'no-product',type:'purchase',category:'BOX',condition:'あり',quantity:1,price:100},'m-no-product'),/product/);assert.deepEqual(s,before)});
test('card number survives purchase and can be corrected with an audit while old quote becomes stale',()=>{let s=applyTransaction(emptyV2(),{id:'p-card',type:'purchase',product:'ブラッキーex',category:'カード',condition:'美品',quantity:1,price:100,set:'MF 044/040'},'m-card');assert.equal(s.inventoryLots[0].set,'MF 044/040');s.marketQuotes.push({lotId:'lot-p-card',price:12000,fresh:true});const next=setCardIdentity(s,'lot-p-card','MF 043/040','m-identity');assert.equal(next.inventoryLots[0].set,'MF 043/040');assert.equal(next.marketQuotes[0].fresh,false);assert.equal(next.transactions[0].set,'MF 043/040');assert.equal(s.inventoryLots[0].set,'MF 044/040');assert.throws(()=>setCardIdentity(s,'lot-p-card','不明','m-bad'),/カード番号/)});
test('PROMO card number is accepted without changing quantity or prior quote',()=>{let s=applyTransaction(emptyV2(),{id:'promo',type:'purchase',product:'ピカチュウ',category:'カード',condition:'良品',quantity:2,price:200},'m-promo');s.marketQuotes.push({lotId:'lot-promo',price:1500,fresh:true});const fixed=setCardIdentity(s,'lot-promo','PROMO 001/SV-P','m-promo-set');assert.equal(fixed.inventoryLots[0].set,'PROMO 001/SV-P');assert.equal(fixed.inventoryLots[0].quantity,2);assert.equal(fixed.marketQuotes[0].price,1500);assert.equal(fixed.marketQuotes[0].fresh,false)});
