import test from'node:test';import assert from'node:assert/strict';import{emptyV2}from'../v2/core.js';import{applyLotteryBatch}from'../v2/lottery-write.js';
test('lottery batch changes only lotteries and revision metadata',()=>{const s=emptyV2();s.revision=4;s.transactions=[{id:'t1'}];s.inventoryLots=[];s.marketQuotes=[{product:'x',price:1}];const n=applyLotteryBatch(s,[{applicationId:'A1',title:'抽選A',store:'店',status:'応募済'}],'m1');assert.equal(n.revision,5);assert.equal(n.lotteries.length,1);assert.deepEqual(n.transactions,s.transactions);assert.deepEqual(n.inventoryLots,s.inventoryLots);assert.deepEqual(n.marketQuotes,s.marketQuotes)});
test('same application id updates instead of duplicating',()=>{const s=emptyV2();s.lotteries=[{id:'l1',applicationId:'A1',title:'抽選A',store:'店',status:'応募済'}];const n=applyLotteryBatch(s,[{applicationId:'A1',title:'抽選A',store:'店',status:'落選',resultDate:'2026-09-23'}],'m2');assert.equal(n.lotteries.length,1);assert.equal(n.lotteries[0].status,'落選');assert.equal(n.lotteries[0].id,'l1')});
test('older application mail cannot downgrade a final result',()=>{const s=emptyV2();s.lotteries=[{id:'l1',applicationId:'A1',title:'抽選A',store:'店',status:'落選'}];const n=applyLotteryBatch(s,[{applicationId:'A1',title:'抽選A',store:'店',status:'応募済'}],'m3');assert.equal(n.lotteries[0].status,'落選')});
test('stale import cannot undo a photo-reported receipt',()=>{const s=emptyV2();s.revision=8;s.lotteries=[{id:'l1',applicationId:'A1',title:'店',store:'店',status:'購入済',receiptStatus:'受取済',receivedDate:'2026-09-20',shrinkStatus:'あり'}];const n=applyLotteryBatch(s,[{applicationId:'A1',title:'店',store:'店',status:'当選',receiptStatus:'未受取',receivedDate:'',shrinkStatus:'未選択'}],'m4');assert.equal(n.lotteries[0].status,'購入済');assert.equal(n.lotteries[0].receiptStatus,'受取済');assert.equal(n.lotteries[0].receivedDate,'2026-09-20');assert.equal(n.lotteries[0].shrinkStatus,'あり')});
test('conflicting terminal result cannot overwrite an existing terminal result',()=>{const s=emptyV2();s.lotteries=[{id:'l1',applicationId:'A1',title:'店',store:'店',status:'当選',receiptStatus:'未受取'}];const n=applyLotteryBatch(s,[{applicationId:'A1',title:'店',store:'店',status:'落選',receiptStatus:'対象外'}],'m5');assert.equal(n.lotteries[0].status,'当選');assert.equal(n.lotteries[0].receiptStatus,'未受取')});
test('identical reimport is a no-op and does not bump revision',()=>{const s=emptyV2();s.revision=9;s.lastMutationId='old';s.lotteries=[{id:'l1',applicationId:'A1',title:'店',store:'店',status:'応募済'}];const n=applyLotteryBatch(s,[{applicationId:'A1',title:'店',store:'店',status:'応募済'}],'m6');assert.equal(n.revision,9);assert.equal(n.lastMutationId,'old');assert.deepEqual(n.auditLog,s.auditLog)});

test('win can progress to purchased with received state',()=>{const s=base();s.lotteries=[{id:'l1',applicationId:'a1',title:'店',store:'店',status:'当選',receiptStatus:'未受取'}];const n=applyLotteryBatch(s,[{applicationId:'a1',title:'店',store:'店',status:'購入済',receiptStatus:'受取済み',receivedDate:'2026-09-24'}],'m4');assert.equal(n.lotteries[0].status,'購入済');assert.equal(n.lotteries[0].receiptStatus,'受取済み');assert.equal(n.lotteries[0].receivedDate,'2026-09-24')});
